#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" final_path)
with_mysql=$(ynh_app_setting_get "$app" with_mysql)

# Copy the app files
DESTDIR="/var/www/${app}"
ynh_backup "$DESTDIR" "sources" 1

# Copy the conf files
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "conf/nginx.conf"
ynh_backup "/etc/php5/fpm/pool.d/${app}.conf" "conf/php-fpm.conf"
ynh_backup "/etc/php5/fpm/conf.d/20-${app}.ini" "conf/php-fpm.ini"

# Backup db
if [[ $with_mysql -eq 1 ]]; then
	root_pwd=$(sudo cat /etc/yunohost/mysql)
	sudo su -c "mysqldump -u root -p$root_pwd --no-create-db $app > ./db.sql"
fi