#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

CLEAN_SETUP () {
# Nettoyage des résidus d'installation non pris en charge par le script remove.
	# Clean hosts
	sudo sed -i '/#SPIP/d' /etc/hosts
}
TRAP_ON	# Active trap pour arrêter le script si une erreur est détectée.

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin_spip=$YNH_APP_ARG_ADMIN
language=$YNH_APP_ARG_LANGUAGE
#multisite=$YNH_APP_ARG_MULTISITE
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

CHECK_VAR "$app" "app name not set"

CHECK_USER "$admin_spip"

CHECK_PATH

CHECK_DOMAINPATH

CHECK_FINALPATH

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path
ynh_app_setting_set $app admin $admin_spip
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app language $language
#ynh_app_setting_set $app multisite $multisite

GENERATE_DB $app	# Créer une base de données et un utilisateur dédié au nom de l'app.

# Crée le repertoire de destination et stocke son emplacement.
sudo mkdir "$final_path"
ynh_app_setting_set $app final_path $final_path

SETUP_SOURCE "spip-3.1.zip"

# Set permissions to spip directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/spip.conf

POOL_FPM

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload

if [ "$is_public" = "No" ];
then
	# Retire l'accès public
	ynh_app_setting_delete $app unprotected_uris
	sudo yunohost app ssowatconf
fi

# Nettoyer hosts
sudo sed -i '/#SPIP/d' /etc/hosts