#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
admin=$(ynh_app_setting_get "$app" admin)
is_public=$(ynh_app_setting_get "$app" is_public)
language=$(ynh_app_setting_get "$app" language)

# Remove trailing "/" for next commands
path=${path%/}

root_pwd=$(sudo cat /etc/yunohost/mysql)

final_path=/var/www/spip

db_name=spip

# Check if admin is not null
if [[ "$admin_spip" = "" || "$is_public" = "" || "$language" = "" ]]; then
	echo "Unable to upgrade, please contact support"
	exit 1
fi


# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*

if [ $is_public = "Yes" ];
then
	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/spip.conf
	# grep -q "define('FORCE_SSL_ADMIN', true);" $final_path/wp-config.php
	# if [[ ! $? -eq 0 ]];
	# then
	#     echo "define('FORCE_SSL_ADMIN', true);" | sudo tee -a $final_path/config/connect.php
	# else 
	#     sudo sed -i "s@//define('FORCE_SSL_ADMIN@define('FORCE_SSL_ADMIN@g" $final_path/config/connect.php
	# fi
else
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/spip.conf
fi

# If app is public, add url to SSOWat conf as skipped_uris
if [[ $is_public -eq 1 ]]; then
	# See install script
	ynh_app_setting_set "$app" unprotected_uris "/"
	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/spip.conf
else
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/spip.conf
fi

# Reload Nginx
sudo service nginx reload
